### PR TITLE
Add Terminal.app color scheme file

### PR DESCRIPTION
**Pull request by markogresak**
I wanted to also use this theme in default terminal, so I created the color scheme. 
I hope I didn't miss anything.

### CODE REVIEW

**Comment by MartinSeeler** [comment]
That's a great idea! 
How did you convert the colors? At a first glance, it seems that some colors are a tiny bit of. I compared the black (`435B66` vs `435B67`) and magenta (`FB226E` vs `FC226E`) and did not check all of the color codes.

**Comment by markogresak** [comment]
First I've tried to find a way to convert color values directly from the file, but noticed that apple is using an encoded value, so decided it would be faster to just use a color picker (dull work) than to find a way for programatic conversion.
Although if there will be any changes, maybe it would be worth the time to look into this, I believe the colors are base64 encoded (more info in [this post](http://apple.stackexchange.com/questions/98655/how-are-colorschemes-represented-in-os-x-terminal-app-settings-files)).

Here are decoded values:

```
ANSIBlackColor 0.262745098 0.3568627451 0.4
ANSIBlueColor 0.2117647059 0.7137254902 0.9960784314
ANSIBrightBlackColor 0.6274509804 0.6901960784 0.7254901961
ANSIBrightBlueColor 0.4392156863 0.8078431373 1
ANSIBrightCyanColor 0.6039215686 0.9960784314 0.9019607843
ANSIBrightGreenColor 0.6784313725 0.9647058824 0.7450980392
ANSIBrightMagentaColor 0.9882352941 0.4039215686 0.6078431373
ANSIBrightRedColor 0.9921568627 0.4549019608 0.431372549
ANSIBrightWhiteColor 1 1 1
ANSIBrightYellowColor 0.9960784314 0.8823529412 0.4274509804
ANSICyanColor 0.3490196078 1 0.8196078431
ANSIGreenColor 0.3607843137 0.9450980392 0.6235294118
ANSIMagentaColor 0.9843137255 0.1333333333 0.431372549
ANSIRedColor 0.9843137255 0.2235294118 0.2588235294
ANSIWhiteColor 1 1 1
ANSIYellowColor 0.9960784314 0.8196078431 0.2
BackgroundColor 0.1098039216 0.1490196078 0.168627451
Font
SelectionColor 0.3058823529 0.4156862745 0.4705882353
TextBoldColor 0.9176470588 0.9176470588 0.9176470588
TextColor 0.9058823529 0.9215686275 0.9333333333
```

**Comment by MartinSeeler** [comment]
Thanks for the link. Maybe I should at the RGB values of the scheme to the README. This way, you can adjust the color values and others can add their applications more easily. Will check this tomorrow.

**Comment by markogresak** [comment]
After some more playing around I've found out that Apple is probably serialising the objects directly from objective-C, therefore we probably can't use a simple shell script to solve this. 
I will check all the colors against the default values, I might have done some changes to my theme, I can't remember for sure.

**Comment by markogresak** [comment]
Closing because lack of interest. I never use terminal.app these days.

**Pull request closed without merging**
